apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: email2rss
  name: email2rss
spec:
  selector:
    matchLabels:
      app: email2rss
  template:
    metadata:
      labels:
        app: email2rss
    spec:
      containers:
      - name: email2rss
        image: us-south1-docker.pkg.dev/homelab-388417/homelab/email2rss:latest
        imagePullPolicy: Always
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/gcp-creds/creds.json
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        volumeMounts:
        - name: gcp-creds
          readOnly: true
          mountPath: /var/gcp-creds
      volumes:
      - name: gcp-creds
        secret:
          secretName: gcp-creds
      imagePullSecrets:
      - name: regcred
